# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 418f36b5177cff32121fc018ec03d917e415b7ad72652773e56c77c8ff3eeace80b8b9678b2f862bb682b5db0dd5b1ef02e50b9129b63a2d3f0a0eabb45ede80

test:
  secret_key_base: 0a71f0cbae345105776d82818db8dae538a106c6e6b211e60f2b82307807fa9005175f84b65e645f3b2ebf03cb8fa4df39d5a904aead7604fe7b8d9cb6046ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
